question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.",
        "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.",
     "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"},
    {"text": "The human body has four lungs.", "answer": "False"},
    {"text": "The Great Wall of China is visible from space.", "answer": "False"},
    {"text": "Bananas grow on trees.", "answer": "False"},
    {"text": "The Atlantic Ocean is the largest ocean on Earth.", "answer": "False"},
    {"text": "Sharks are mammals.", "answer": "False"},
    {"text": "The capital of Australia is Sydney.", "answer": "False"},
    {"text": "Some cats are allergic to humans.", "answer": "True"},
    {"text": "Octopuses have three hearts.", "answer": "True"},
    {"text": "Goldfish only have a memory of three seconds.", "answer": "False"},
    {"text": "Lightning never strikes in the same place twice.", "answer": "False"},
    {"text": "Honey never spoils.", "answer": "True"},
    {"text": "The human nose and ears continue to grow throughout life.", "answer": "True"},
    {"text": "An ostrich's eye is bigger than its brain.", "answer": "True"},
    {"text": "Bats are blind.", "answer": "False"},
    {"text": "Venus is the closest planet to the Sun.", "answer": "False"},
    {"text": "Water boils at a higher temperature on top of a mountain.", "answer": "False"},
    {"text": "The unicorn is the national animal of Scotland.", "answer": "True"},
    {"text": "Polar bears' skin is black.", "answer": "True"}
]


